### ISSUE TITLE
Cars placed too close to track end

### ISSUE THREAD

**Issue by Voidheartd** [SgtMoloch/MoveTheEquipment#1]
The cars are being left too close to the front of the Whittier interchange. This happened twice, once when I bought 2 coal cars, and it moved the second one too close. and then again when it moved both cars for the interchange service.

![image](https://github.com/SgtMoloch/MoveTheEquipment/assets/3398909/e9c4fefb-1a42-47e5-9c8e-d16ef58b8608)

**Comment by SgtMoloch** [comment]
Do you have logs from this? 

To make sure I understand correctly:

“it moved the second one too close”:
It moved the second one in front of the first one? 

As for them being too close, this wasn’t something I observed in my testing. If you could tell me where the cars were in relation to each other and in relation to the front of the track when it moved them, that would help me recreate the issue.

**Comment by SgtMoloch** [comment]
Also, I have not validated this mod with the latest version of Railroader.

**Comment by Voidheartd** [comment]
I purchased 2 coal cars one at a time. When I purchased the second one, the first one was moved to the front of the interchange, in the same place the front car is in the screenshot. 

The next time the interchange was serviced, the 2 coal cars were moved to the front of the interchange, again too close to the switch, as can be seen in the screenshot.

**Comment by Voidheartd** [comment]
I recreated the initial scenario (buying 2 coal cars 1 at a time) to provide a log.
[railloader.log](https://github.com/SgtMoloch/MoveTheEquipment/files/13896811/railloader.log)
![image](https://github.com/SgtMoloch/MoveTheEquipment/assets/3398909/610e7d4d-e9fb-4862-96cc-5b31f0f62e3f)

**Comment by SgtMoloch** [comment]
Thanks for the log! I will look into this. Will be a couple of days due to being swamped at work.

**Comment by SgtMoloch** [comment]
Shoot me a msg on discord and can work through it. Worst case I’ll post up the DLL for this beta version

**Comment by Voidheartd** [comment]
What's your discord id? I couldn't find anything matching you on the rr discord. Or you can send me a message, I am Voidheart on the rr discord.

**Comment by SgtMoloch** [comment]
sgtmoloch

I tried to send you a msg/add friend but it won’t let me. I tagged you in a post on the mod thread just now.

**Comment by SgtMoloch** [comment]
Maybe you accidentally blocked me?

**Comment by Voidheartd** [comment]
Fixed with 621e36f
