### ISSUE TITLE
Moved cars crash into train located at end of interchange track

### ISSUE THREAD

**Issue by Voidheartd** [SgtMoloch/MoveTheEquipment#2]
I found that having a steam locomotive sitting at the end of the interchange track causes a moved coal car to spawn colliding with the train. The coal car was shoved backward and derailed due to this. The tender of the train it collided with was damaged to 56%. It happened when I purchased another locomotive.
[railloader.log](https://github.com/SgtMoloch/MoveTheEquipment/files/13937069/railloader.log)
![image](https://github.com/SgtMoloch/MoveTheEquipment/assets/3398909/5f1c5650-6271-4ec8-8ccb-5814afbd9a41)

**Comment by SgtMoloch** [comment]
I’ll point to the blurb in the readme about steam engines and this mod. 

That said, the logic it’s using to move the cars is the same as the logic it uses to find a spot to place a car normally. 

I plan on fixing a couple bugs I’ve found personally with this mod later today. 

In the meantime, just keep your engines clear of the north end of the track. 

Also, I still have not fully validated this mod with the latest game version. So unexpected behavior can and will happen. Apologies that it’s taken awhile, as I said in the other thread I’ve been swamped with work and haven’t had time to dedicate to bug fixing.

**Comment by SgtMoloch** [comment]
I have a beta build of the mod that I would like for you to try @Voidheartd . Would you be willing to do that?

**Comment by Voidheartd** [comment]
Sure, I've been testing the latest commits of route manager as well.

**Comment by SgtMoloch** [comment]
> Sure, I've been testing the latest commits of route manager as well.

awesome. If you pull the dev branch. Let me know if you need assistance building it locally.

**Comment by SgtMoloch** [comment]
should be fixed by #4
