### ISSUE TITLE
Company Equipment with different reporting mark not being moved

### ISSUE THREAD

**Issue by Velenka1** [SgtMoloch/MoveTheEquipment#5]
Using MoveTheEquipment 2.0.0 and InterchangeUnchained 1.2.2 on Railroader 2024.1.0a and Railloader 1.1.24018.2314

Tried to get the interchange serviced with three company cars (diesel tank and two coal cars). The equipment isn't moved and causes the interchange to be at capacity when the service occurs. I don't know if I'm missing something but it seems like this should work? I could have sworn that when I first installed the mod, I tested it and it did work. The Interchange Unchained mod seems to be working (all 3 tracks get cars although that can't be seen from the after screenshot) but not MoveTheEquipment.

Before:
![before](https://github.com/SgtMoloch/MoveTheEquipment/assets/157774628/c5a0a0fe-f7a3-4043-b1a4-2c1cd3af8707)

After:
![after](https://github.com/SgtMoloch/MoveTheEquipment/assets/157774628/549bab60-e911-4c50-b174-606abc4e3e34)

Railloader log:
[railloader.log](https://github.com/SgtMoloch/MoveTheEquipment/files/14059939/railloader.log)

**Comment by SgtMoloch** [comment]
Do you have the log from when the interchange got serviced? That log only has the startup of the game. I would need more than that to go on. I’ve tested it and have not encountered such an issue. 

Also, to be clear, there were no steam engines anywhere near the interchange track when it was serviced, correct? Like, even a coupler from a tender would cause it to not move cars.

**Comment by Velenka1** [comment]
I can confirm that there is not any steam engine in the interchange.

I saved the game just prior to sleeping. I started Railroader, started the save, slept, waited until the interchange was served, then saved the game and exited. Here is the log for that session. If there's another log somewhere I need to get, let me know.

[railloader.log](https://github.com/SgtMoloch/MoveTheEquipment/files/14060555/railloader.log)

**Comment by SgtMoloch** [comment]
Thanks, that’s more helpful. 
2 more questions @Velenka1 

1. What is your railroad reporting mark?
2. Do the reporting marks on those cars differ from your railroad reporting mark?

**Comment by SgtMoloch** [comment]
Also, could you send me your save so I can do some testing with it?

First blush tells me something is funky somewhere. But I need more logging to figure out this edge case.

**Comment by Velenka1** [comment]
> Thanks, that’s more helpful. 2 more questions @Velenka1
> 
>     1. What is your railroad reporting mark?
> 
>     2. Do the reporting marks on those cars differ from your railroad reporting mark?

I know that we did change the reporting mark on our (BVRR) cars as a reference to one of our friend's railway (BJ&HC). I changed it back and performed another test. The equipment movement is successful after the interchange service. So it seems we will need to keep our cars named with our own reporting mark only?

**Comment by SgtMoloch** [comment]
Yeah, basically I’m checking all cars on a track and if the reporting mark doesn’t match your RR reporting mark, I assume that it is a non company car and don’t move anything on that track. 

I can look into maybe making this check more robust, though I’m unsure if there is a way to or not.

In the meantime, as long as when they are in the interchange and have the appropriate reporting mark, they will be moved.

**Comment by SgtMoloch** [comment]
@Velenka1 try the latest release v2.1.0, it should fix your problem.

**Comment by Velenka1** [comment]
Indeed it does. Thanks for the fix!
