### ISSUE TITLE
Trains reversing direction when moved

### ISSUE THREAD

**Issue by Fevix** [SgtMoloch/MoveTheEquipment#7]
I have all of my locomotives lined up so that "forward" is westbound. After installing this mod and leaving a small mess at an interchange to test, I found that when the interchange was served, one of my locomotives was reversed, now facing eastbound. It wasn't too much of an issue, as I had two cars (fuel) that needed to go to Dilsboro, so I could just send it there and use the turntable, but it could have been worse if I had multiple trains turned around like this.

**Comment by SgtMoloch** [comment]
There isn’t much I can do about this, as how the game places the train seems to not be consistent. 

Also, with the new update, this mod is now obsolete.
