### ISSUE TITLE
Broken after RR 2024.4.0

### ISSUE THREAD

**Issue by Exp232** [SgtMoloch/MoveTheEquipment#9]
[message.txt](https://github.com/SgtMoloch/MoveTheEquipment/files/15396383/message.txt)

**Comment by Exp232** [comment]
Mod isn't playing nicely with the new 24 hour wait period imposed for Fuel/repair parts. Removal fixes the issue.

**Comment by bischoffz** [comment]
Thanks for the report. To be clear, now that company cars go away for a day, this mod is more or less obsolete. 

So I do not think I will be updating this mod going forward.

**Comment by SgtMoloch** [comment]
Thanks for the report. 

Because the new update effectively makes this mod obsolete, I do not plan on updating it unless there is actual demand for it. 

Best to keep it removed and advise others to do the same.
